### ISSUE TITLE
Use parameter without tag

### ISSUE THREAD

**Issue by cowboy3d** [hellflame/argparse#14]
Hi!

First I‘d like to thank you for your work - coming from Python this helps quite a lot.
There is one case I don‘t seem to be able to solve - is something like 
program -v -d  input.txt
feasible, where -v and -d are only flags and input.txt is a parameter that is used as input for program?

Kind regards

Stephan

**Comment by hellflame** [comment]
do you mean like this ?

```go
parser := argparse.NewParser("", "", nil)
v := parser.Flag("v", "", nil)
d := parser.Flag("d", "", nil)
f := parser.String("f", "", &argparse.Option{Positional: true})
if e := parser.Parse(nil); e != nil {
	print(e.Error())
	return
}
println("v =>", *v)
println("d =>", *d)
println("f =>", *f)
```

**Comment by cowboy3d** [comment]
Just perfect - looks easy... once you know how to do it.

Thanks a lot.

**Comment by hellflame** [comment]
thanks for using this repo :)
