### ISSUE TITLE
Struct for Commands and Routing by them

### ISSUE THREAD

**Issue by FeliaDev** [hellflame/argparse#16]
First of all, your works is awesome, it's super powerful this package. 

I'm using a lot for creating CLIs, I repeat the same patron over and over because I really like to use "commands".

```go
package main

import "github.com/hellflame/argparse"

// Struct as args command container
type FooCommand struct {
  A *string
  B *string
}

// Execute method of the command
func (f *FooCommand) execute() string {
  if f.A == "bar" {
    panic(fmt.Error("a panic"))
  }
  return f.B+f.A 
}

// Mapping the command args over the Struct
func NewFooCommand(p *argparser.Parser) *FooCommand {
  return &FooCommand{
    A: p.String("", "a", &argparse.Option{
      Required:   true,
      Positional: true,
    })
    B: p.String("", "b", &argparse.Option{
      Required:   true,
      Positional: true,
    })
  }
}

// Create the parser and the command containers
func main(){
  parser := argparser.NewParser("cli", "my super awesome cli", nil)
  fCmd := NewFooCommand(parser.AddCommand("foo", "allows to foo", nil))
  
  if e := parser.Parse(nil); e != nil {
    fmt.Println(e)
    return
  }
  
  // Using a switch for routing
  switch os.Args[1]{
  case "foo":
    fmt.Println(fCmd.execute())
  } 
  
}
```

I took a look to the source code, but I could not able to see an easy way to routing by the current command. 

So, my idea is the Command Container Struct implements an interface which contains the "execute" method, and internally the Parser could call to that method based on the os.Args[1] (the current command). This add two problems, register the command based on Command Container and retrieve the info from the execute command after executed.

I think, adding two new method to the Parser, for keep safe the backward compatibility, is the best.

Those methods are: 
- `p.AddCommandContainer(name string, description string, mapping func(*parser) *CommandContainer)`
  - Will register the command, and receive a callback for mapping, and return an implementation of CommandContainer.

- `p.Result() string`
  - Will retrieve the data cached in the Parser of the executed command.

Also the method `p.Parse()` will be in charge of executing the CommandContainer "execute" method.

I don't know if this idea goes against the original idea of the package, but all is for the good of the package.

I hope someday this package become a de facto package for Golang.

**Comment by hellflame** [comment]
Well, I can see the idea of Commands struct, which can make creating arguments easier and more beautiful.
But I'm a little confused of the later one

> the Parser could call to that method based on the os.Args[1]

Is there any actual scenario about it? I want to know more about how would you use it, so that we can get the same picture ,or even get better solution for that.

**Comment by FeliaDev** [comment]
May I did not express well.
For my scenario, I have several "Commands" (SubParsers) at level 1

`cli {a, b, c, d} [a[...], b[...], c[...], d[...]]`.

So, how the parser change the flow of the program based on the command (os.Args[1])?. 
At my knowledge, I did not found any easy clean solution but a Switch statement.
 
 ```go
 switch os.Args[1]{
 case "a":
    fmt.Println(fCmd.execute())
 case "b":
  ...
  case "c":
  ...
 } 
 ```
 But I don't like it because the responsibility of the arguments bellows to the Parser, not the user.
 
All of this loses sense if there is already a way to routing the program based on the commands (and subcomands, and so on).

This problem even is not solved in Python Argparse. You have to do a workaround for change the flow of the program, using a dict of callbacks as a switch or even declare if statement by if statement.
 
 The final image I have is this:
 
 ```go
type CommandContainer interface {
  Execute() string // or whatever, generic may be.
}

type FooCommand struct {
  A *string
  B *int
}

func (c *FooCommand) Execute() string {
  if c.B > 20 {
    return c.A
  } else {
    return c.A+"Bar"
  }
} 
 
func main(){
  parser := argparser.NewParser("cli", "my super awesome cli", nil)
  parser.AddCommandContainer("foo", "allows to foo", func (p *parser) *CommandContainer{
     return &FooCommand{
       A: p.String("", "a", nil),
       B: p.Int("", "a", nil)
     }
  })
 
  if e := parser.Parse(nil); e != nil {
    fmt.Println(e)
    return
  }
  fmt.Println(parser.Result()) // Print the output of the Execute method.
}
 ```
 Also thinking about the testing part of the program, this way allows to test every single part. 
 
 I hope I made me to understand. (I'm from Argentina 🇦🇷 , not good english speaker)

**Comment by hellflame** [comment]
Thanks for the detailed code, I can understand more about what you wanted.
As the code showed
```go
switch os.Args[1]{
case "a":
   fmt.Println(fCmd.execute())
case "b":
 ...
 case "c":
 ...
} 
```
It's more like just `subCommand`

```go
parser := argparse.NewParser("sub", "", nil)

aParser := parser.AddCommand("a")

aParser.InvokeAction = func(invoked bool) {
    // do something like `fCmd.execute()`
    // code here will only be executed when user input `sub a xxx ......`
    // and will more efficient than `switch os.Args[1]` there.
}
```

You can find more info about `invoked` [here](https://github.com/hellflame/argparse#14-invoked--invokeaction---140-)
And here is a not-quite elegant way of [batch create arguments](https://github.com/hellflame/argparse/blob/master/examples/batch-create-arguments) , if there are a lot arguments to create, you can iterate over your argument struct instead. Sure, I'll consider making it easier and more beautiful to create arguments in the future pushes.

I guess the main issue can be solved by [sub command](https://github.com/hellflame/argparse#9-subcommands) and the `invoked` action. You can check it out.

It's ok, I'm not a native speaker either 😺 . However, we have code in common.
> I hope I made me to understand. (I'm from Argentina 🇦🇷 , not good english speaker)

**Comment by FeliaDev** [comment]
Gracias!.
