### ISSUE TITLE
No way to determine which subcommand was called

### ISSUE THREAD

**Issue by lespea** [hellflame/argparse#2]
**Describe what you want**

Currently, as far as I can tell, there is no actual way to determine which subcommand was called.  I was initially using `DefaultAction` to automatically invoke the sub command's functionality but then I discovered that default action is only called when there are no flags?  That is extremely confusing and I guess I see it's documented that it's suppose to replace the "help" functionality? but that is definitely not expected given the name.

I have a lot of subcommands so each one is responsible for adding itself to the global parser and setting up the runtime function to call when it's being invoked by the user; it's not feasible to use a massive list of "global" flags and guess which one is being called.

The current `DefaultAction` is definitely not ideal anyway as you need to add it *before* you add any flags so I have this convoluted system where I swap a pointer to a function after setting up the flags.

I came here from https://github.com/akamensky/argparse/ (which has it's own issues) and there I had to loop over all of the subcommands to figure out which one was ran, which wasn't the greatest but still worked.  The easiest solution, but far from the greatest design, would allow you to set a subcommand's "run function" after it's been created, so that you can easily get access to the flags that were set.  If not that, then maybe borrow a page out of `akamensky`?

It's definitely possible I'm just missing something and this already exists so if that's the case my apologies and I would appreciate some pointers on what I'm not seeing.

**Why is it necessary**

Makes multiple subcommands usable

**Test case examples** [Optional]

This is just super thrown together so sorry it's not great...

```go
parser := argparse.NewParser("test", "testing", nil)

sc1 := parser.addCommand("sub1", "sub command 1", nil)

f1 := sc1.Flag("a", "flag1", nil)
f2 := sc2.Flag("b", "flag2", nil)

sc2.SetInvokeFunc(func(){
    fmt.Printf("%v - %v\n", *f1, *f2)
})
```

-- or --

```go
parser := argparse.NewParser("test", "testing", nil)

sc1 := parser.addCommand("sub1", "sub command 1", nil)

f1 := sc1.Flag("a", "flag1", nil)
f2 := sc2.Flag("b", "flag2", nil)

parser.Parse([]string{"sub1", "-a"})

assert(sc1.Invoked() == true)
```

**Comment by hellflame** [comment]
It's a good idea to know which subcommand was called

the idea is just been accepted !

**Comment by lespea** [comment]
Oh awesome, thanks for implementing this so quickly!  I'm updating everything now and will update once I validate it works for my use case (which it definitely should).

**Comment by lespea** [comment]
Looks like the wrong parser Invoked is being set... observe:

```go
func main() {
	o := &argparse.ParserConfig{
		DisableDefaultShowHelp: true,
	}

	p := argparse.NewParser("test", "test desc", o)
	sub := p.AddCommand("sub", "sub cmd", nil)

	if err := p.Parse(nil); err != nil {
		panic(err)
	}

	fmt.Printf("%v - %v\n", p.Invoked, sub.Invoked)
}
```

Output:
```
❯ ./test
false - false
❯ ./test sub
true - false
```

I would expect the first to be `true - false` and the second to be `false - true`.  I also think that `DisableDefaultShowHelp` should default to false and you should opt in to that... it doesn't really make sense to default to showing help just because there were no args...  I can see where you might want that but that would be an edge case imo.

**Comment by hellflame** [comment]
well, we might have a different definition of `Invoked`. 

only when there's any input for the parser, the parse action can proceed, this is `Invoked`, and you have argument values to proceed. 

here,  `sub` command is actually part of main parser. when the input reached sub parser, it can't miss the main parser, which cause `p.Invoked == true`. as the sub parser has no input, it got nothing to parse, then it's not `Invoked`.

if you want to do something when there is no input, do it this way:

```go
parser := argparse.NewParser("basic", "", &argparse.ParserConfig{DefaultAction: func() {
  fmt.Println("hi ~\ntell me what to do?")
  fmt.Println("do things when main parser has no input")
}})
parser.AddCommand("test", "testing", &argparse.ParserConfig{DefaultAction: func() {
  fmt.Println("ok, now you know you are testing")
  fmt.Println("do things when test parser has no input")
}})
```

**Comment by lespea** [comment]
The current method requires you to split functionality between DefaultAction and Invoked which makes this library extremely difficult to use.  There are many types of "actions" or subcommands that take no parameters and just perform some task, so you are invoking it even if you don't have additional args

**Comment by lespea** [comment]
Oh sorry I see you commented in my PR, I guess we'll just discuss here.  If this is something that we just disagree with that's fine, but I'll be switching libraries then unfortunately.

**Comment by hellflame** [comment]
emmmm.....I don't think using DefaultAction & Invoked instead of just one function will make it that `extremely` difficult to use. But you got some point, I'll change a little for InvokeAction.

> The current method requires you to split functionality between DefaultAction and Invoked which makes this library extremely difficult to use. There are many types of "actions" or subcommands that take no parameters and just perform some task, so you are invoking it even if you don't have additional args

**Comment by lespea** [comment]
Your version still doesn't fix invoked when parsed is called multiple times and you didn't include any of my tests that actually test it works as expected.  Best of luck with your library but we definitely don't agree with how an argument parser should function.

**Comment by hellflame** [comment]
this is the way I expect the parse to work for most users. Feel free to do any modification in your version, lucky for you.
