### ISSUE TITLE
parser.Parse `args` evaluation

### ISSUE THREAD

**Issue by tiararodney** [hellflame/argparse#7]
Thank you for sharing this module! It is a great improvement upon `github.com/akamensky/argparse`.

I have a question regarding your design choices:

Why does a parser always consider an empty [`args` array](https://github.com/hellflame/argparse/blob/master/parse.go#L373) to be faulty ([parse.go#L382](https://github.com/hellflame/argparse/blob/master/parse.go#L382))? There are situations where all arguments are not required, thus the parser should be satisfied with an empty `args` array.

```golang
package main

import (
	"fmt"
	"github.com/hellflame/argparse"
)

func main() {
	parser := argparse.NewParser("foo", "", nil)

	sampleArg := parser.String("", "sample", &argparse.Option{
		Required: false,
	})

       	var argv []string

        // will evaluate to true, even though all argument requirements are satisfied
	if e := parser.Parse(argv); e != nil {
		fmt.Println(e.Error())
		return
	}

	fmt.Print(*sampleArg)
}
```

**Comment by hellflame** [comment]
thanks for using this module, and such close code review, this always helped me improve this argparse.

the reason of doing so really is out of one consideration. 

`empy args` is a special case, which mostly users don't know what to do. so the help menu will be printed by default, 
which can be changed in the `ParserConfig` with `DisableDefaultShowHelp: true`

hope this example will help your situation:

```go
package main

import (
	"fmt"
	"github.com/hellflame/argparse"
)

func main() {
	parser := argparse.NewParser("foo", "", &argparse.ParserConfig{
		DisableDefaultShowHelp: true,
	})

	sampleArg := parser.String("", "sample", &argparse.Option{
		Required: false,
		Default: "simple",  // it's ok not to set default value,
		// but to show you the default value can be bind to `sampleArg`
	})

	var argv []string

	if e := parser.Parse(argv); e != nil {
		fmt.Println("there is no error")
		fmt.Println(e.Error())
		return
	}

	fmt.Print("here => ", *sampleArg)
}

```

**Comment by hellflame** [comment]
you can find more config reference here [https://github.com/hellflame/argparse/blob/master/README.md#1-parserconfig](https://github.com/hellflame/argparse/blob/master/README.md#1-parserconfig)

if there is still any problem, and if there is enough reason for doing so, I'll be glad to make a new release
